on:
  schedule:
  - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable
      env:
        GITH_EMAIL: j1g5aw@foxmail.com
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SKIP_UPDATED: '1'
